#!/bin/bash

HOME=/home/viage
app=block_hash
base=$HOME/work/$app
perlver=5.14.4

source $HOME/.bash_profile
carton=$HOME/.plenv/versions/$perlver/bin/carton

echo '###'
echo '### The following commands are executed from ".git/hooks/post-merge".'
echo '###'
cd $base
echo ''
echo '### Install dependence modules ...'
$carton install --cached
echo ''
echo '### Current application pid...'
ps auxf | egrep 'script/block_hash|starman'
echo ''
echo '### Restart application ...'
kill -HUP `pgrep -f script/$app`
sleep 2
echo ''
echo '### Current application pid...'
ps auxf | egrep 'script/block_hash|starman'
echo ''
echo '### End of port-merge'
