insert into hashtag (hashtag, title, created_at) values ('remo_con', 'Remote Control', now());
insert into hashtag (hashtag, title, created_at) values ('localize', 'Localize!!', now());
insert into hashtag (hashtag, title, created_at) values ('Basstech', 'BASS TECH', now());
insert into hashtag (hashtag, title, created_at) values ('hedkandiradio', 'Hed kandi Radio', now());
insert into hashtag (hashtag, title, created_at) values ('mosradio', 'Ministry of Sound Radio', now());
insert into hashtag (hashtag, title, created_at) values ('tcyradio', 'TCY RADIO', now());
insert into hashtag (hashtag, title, created_at) values ('oirantv', 'shibuya OIRAN warm up Radio', now());
insert into hashtag (hashtag, title, created_at) values ('urbanslice', 'URBAN SLICE', now());
insert into hashtag (hashtag, title, created_at) values ('blockfm', 'Morley Robertson Show', now());
insert into hashtag (hashtag, title, created_at) values ('Hyper_Society', 'Hyper Society', now());
insert into hashtag (hashtag, title, created_at) values ('tjo', 'Smooth Navigation', now());
insert into hashtag (hashtag, title, created_at) values ('date_line', 'Date Line', now());
insert into hashtag (hashtag, title, created_at) values ('tony', 'T.O.N.Y', now());
insert into hashtag (hashtag, title, created_at) values ('カタカナdeハベル', 'カタカナdeハベル', now());
insert into hashtag (hashtag, title, created_at) values ('no_bias', 'WASABEAT MUSIC SHOWCASE "NO BIAS"', now());
insert into hashtag (hashtag, title, created_at) values ('Wickedpedia_Radio', 'Wickedpedia Radio', now());
insert into hashtag (hashtag, title, created_at) values ('raidsystem', 'Future Beat Maniax', now());
insert into hashtag (hashtag, title, created_at) values ('yone_bfm', 'THE NIGHT SAVED MY LIFE', now());
insert into hashtag (hashtag, title, created_at) values ('agx', 'AUDIO GALAXY', now());
insert into hashtag (hashtag, title, created_at) values ('NewDJ_bfm', 'New DJ\'s On The Block', now());
insert into hashtag (hashtag, title, created_at) values ('radio_REBOOT', 'radio REBOOT', now());
insert into hashtag (hashtag, title, created_at) values ('VINYL_HOUSE', 'VINYL HOUSE', now());
insert into hashtag (hashtag, title, created_at) values ('bakass', 'BAKASS', now());
insert into hashtag (hashtag, title, created_at) values ('SECOND_SPACE', 'SECOND SPACE', now());
insert into hashtag (hashtag, title, created_at) values ('iflyer_bfm', 'What\'s going on?', now());
insert into hashtag (hashtag, title, created_at) values ('sodeyama_bfm', 'イマココニイルキミ。', now());
insert into hashtag (hashtag, title, created_at) values ('EDM_Essentials', 'iLOUD presents EDMEssentials', now());
insert into hashtag (hashtag, title, created_at) values ('dont_blink', 'don\'t_blink', now());
insert into hashtag (hashtag, title, created_at) values ('SDM_RADIO', 'SDM RADIO', now());
insert into hashtag (hashtag, title, created_at) values ('swing_chop', 'SWING CHO', now());
insert into hashtag (hashtag, title, created_at) values ('混ぜると危険', 'Absolute Mind Oscillator', now());
insert into hashtag (hashtag, title, created_at) values ('STEPPASIDE', 'STEPPASIDE', now());
insert into hashtag (hashtag, title, created_at) values ('Dancing_Dead', 'Dancing Dead feat. Oddity', now());
insert into hashtag (hashtag, title, created_at) values ('PIW', 'teder.fm & block.fm presents Paint it White', now());
insert into hashtag (hashtag, title, created_at) values ('GWIGGWIGRADIO', 'GWIG GWIG RADIO', now());
insert into hashtag (hashtag, title, created_at) values ('blockfmeden', 'EDEN', now());
insert into hashtag (hashtag, title, created_at) values ('KitsuneRadiobyBeatauCue', 'Kitsuné Radio', now());
insert into hashtag (hashtag, title, created_at) values ('blockfm', 'Toolroom Knights Radio ShowKitsuné Radio', now());
insert into hashtag (hashtag, title, created_at) values ('SUMMIT_bfm', 'SUMMITimes', now());
insert into hashtag (hashtag, title, created_at) values ('blockstepper', 'Block Stepper', now());
